import { type FormEvent } from "react";
import { type Partner } from "../../api/client";
import { type Agreements, type Engagement, type Organization } from "./types";
export function AgreementsEditor({ data, organizations, agreements, partners, save, pending }: { data?: Engagement; organizations: Organization[]; agreements?: Agreements; partners: Partner[]; save: (path: string, body: unknown) => void; pending: boolean }) {
 const options = organizations.map(o => <option key={o.id} value={o.id}>{o.legal_name}</option>);
 function submit(e: FormEvent<HTMLFormElement>, path: string) { e.preventDefault(); const form = new FormData(e.currentTarget); const body: Record<string, unknown> = Object.fromEntries([...form].map(([k, v]) => [k, v || null])); if (path === "/contracts" && data) Object.assign(body, { opportunity_id: data.opportunity_id, expected_version: data.commercial_version }); if (path.endsWith("/vendors") && data && path !== "/vendors") body.expected_version = data.commercial_version; save(path, body); }
 return <div className="commercial-forms"><form className="content-card compact-form" onSubmit={e => submit(e, "/organizations")}><h2>Organization identity</h2><p>Reuse one legal entity across customer, partner and vendor profiles.</p><label>Legal name<input required name="legal_name" minLength={2} /></label><label>Unique business identifier<input required name="identifier" minLength={2} placeholder="Registration or tax identifier" /></label><button disabled={pending}>Create organization</button></form>
 <form className="content-card compact-form" onSubmit={e => submit(e, "/vendors")}><h2>Vendor profile</h2><label>Existing organization<select name="organization_id" required>{options}</select></label><label>Provider category<input name="category" required minLength={2} /></label><label>Commercial contact<input name="commercial_contact" required minLength={2} /></label><button disabled={pending}>Add vendor profile</button></form>
 <form className="content-card compact-form" onSubmit={e => submit(e, "/partner-agreements")}><h2>Partner agreement</h2><label>Partner<select name="partner_id" required>{partners.map(p => <option key={p.id} value={p.id}>{p.company_name}</option>)}</select></label><label>Capability<select name="engagement_model"><option>RESELLER</option><option>REFERRAL</option><option>SYSTEM_INTEGRATOR</option></select></label><label>Effective from<input name="effective_from" type="date" required /></label><label>Effective until<input name="effective_until" type="date" /></label><label>Private document ID<input name="document_id" /></label><button disabled={pending}>Create partner agreement</button></form>
 <form className="content-card compact-form" onSubmit={e => submit(e, "/vendor-agreements")}><h2>Vendor agreement</h2><label>Provider organization<select name="provider_organization_id" required>{options}</select></label><label>Contracting buyer<select name="buyer_organization_id" required>{options}</select></label><label>Charge model<select name="charge_model"><option>LICENSE</option><option>USAGE</option><option>INFRASTRUCTURE</option><option>SERVICE</option></select></label><label>Billing basis<textarea name="billing_basis" required minLength={2} /></label><label>Effective from<input name="effective_from" type="date" required /></label><label>Effective until<input name="effective_until" type="date" /></label><label>Private document ID<input name="document_id" /></label><label>Secret manager reference (optional)<input name="secret_reference" placeholder="secret://provider/credential" pattern="secret://[a-zA-Z0-9/_.-]+" /></label><button disabled={pending}>Create vendor agreement</button></form>
 {data && <><form className="content-card compact-form" onSubmit={e => submit(e, `/opportunities/${data.opportunity_id}/vendors`)}><h2>Link vendor obligation</h2><label>Vendor agreement<select required name="agreement_id">{agreements?.vendors.map(a => <option key={a.id} value={a.id}>{organizations.find(o => o.id === a.provider_organization_id)?.legal_name} · {a.charge_model}</option>)}</select></label><label>Component<select name="component_id"><option value="">Entire opportunity</option>{data.components.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Payer<select name="payer_organization_id" required>{options}</select></label><label>Usage responsibility<textarea required name="usage_responsibility" minLength={2} /></label><label>Cost (USD)<input name="amount" required type="number" min="0" step="0.01" /></label><label>Cost treatment<select name="cost_treatment"><option value="SEPARATE">Separate obligation</option><option value="POOL_DEDUCTION">Explicit pool deduction</option></select></label><button disabled={pending}>Link vendor cost</button></form>
 <form className="content-card compact-form" onSubmit={e => submit(e, "/contracts")}><h2>Contract / amendment</h2><label>Seller<select name="seller_organization_id" required>{options}</select></label><label>Buyer<select name="buyer_organization_id" required>{options}</select></label><label>Contract kind<select name="kind"><option>CUSTOMER</option><option>WHOLESALE</option><option>PROJECT</option></select></label><label>Signed terms / amendment document ID<input name="document_id" /></label><button disabled={pending}>Create draft contract</button>{data.contracts.map(c => <div key={c.id}><strong>{c.kind} · {c.status}</strong><small className="commercial-reference">{c.id}</small></div>)}</form></>}
 </div>;
}
