import { useState, type FormEvent } from "react";
import { engagementModels, type Deal, type Partner, type Product } from "../../api/client";
import { roles, label, type Component, type Engagement, type Organization, type Participant, type Role } from "./types";

export function EngagementEditor({ data, deal, organizations, partners, products, save, pending }: { data: Engagement; deal: Deal; organizations: Organization[]; partners: Partner[]; products: Product[]; save: (body: unknown) => void; pending: boolean }) {
  const [model, setModel] = useState(data.engagement_model ?? "DIRECT");
  const [participants, setParticipants] = useState<Participant[]>(data.participants);
  const [assignments, setAssignments] = useState<Role[]>(data.roles.map(r => ({ organization_id: data.participants.find(p => p.id === r.participant_id)?.organization_id, role: r.role, scope: r.scope, primary: r.is_primary })));
  const [components, setComponents] = useState<Component[]>(data.components);
  const orgOptions = organizations.map(o => <option key={o.id} value={o.id}>{o.legal_name}</option>);
  function submit(e: FormEvent<HTMLFormElement>) {
    e.preventDefault(); const form = new FormData(e.currentTarget);
    save({ expected_version: data.commercial_version, engagement_model: model, partner_id: form.get("partner") || null, responsible_user_id: form.get("responsible") || null, amendment_reason: form.get("amendment") || null,
      participants: participants.map(({ organization_id, capability, access_level, active }) => ({ organization_id, capability, access_level, active })), roles: assignments,
      components: components.map(c => ({ id: c.id, name: c.name, product_id: c.product_id, sku_id: c.sku_id, external_service: c.external_service, owner_organization_id: c.owner_organization_id, seller_organization_id: c.seller_organization_id, delivery_organization_id: c.delivery_organization_id, billing_organization_id: c.billing_organization_id, amount: c.amount })) });
  }
  function changeParticipant(index: number, patch: Partial<Participant>) { setParticipants(old => old.map((p, i) => i === index ? { ...p, ...patch } : p)); }
  function changeRole(index: number, patch: Partial<Role>) { setAssignments(old => old.map((r, i) => i === index ? { ...r, ...patch } : r)); }
  function changeComponent(index: number, patch: Partial<Component>) { setComponents(old => old.map((c, i) => i === index ? { ...c, ...patch } : c)); }
  return <form className="content-card compact-form" onSubmit={submit}><h2>Participants & responsibilities</h2><p>Capability and access are separate. Commercial changes require reapproval; accepted contracts require an amendment.</p><div className="form-grid">
    <label>Primary engagement<select value={model} onChange={e => setModel(e.target.value as typeof model)}>{engagementModels.map(m => <option key={m}>{m}</option>)}</select></label>
    <label>Primary commercial partner<select name="partner" defaultValue={deal.partner_id ?? ""} required={model !== "DIRECT"}><option value="">No partner</option>{partners.filter(p => model === "DIRECT" || p.capabilities.some(c => c.code === model)).map(p => <option key={p.id} value={p.id}>{p.company_name}</option>)}</select></label>
    <label>Internal accountable user ID<input name="responsible" defaultValue={deal.responsible_user_id ?? ""} /></label><label>Amendment reason<input name="amendment" placeholder="Required after contract acceptance" minLength={3} /></label></div>
    <fieldset><legend>Explicit opportunity membership</legend>{participants.map((p, i) => <div className="commercial-row" key={i}><label>Organization<select required value={p.organization_id} onChange={e => changeParticipant(i, { organization_id: e.target.value })}><option value="">Select organization</option>{orgOptions}</select></label><label>Capability<select value={p.capability ?? ""} onChange={e => changeParticipant(i, { capability: e.target.value || null })}><option value="">Internal / customer / vendor</option>{engagementModels.filter(m => m !== "DIRECT").map(m => <option key={m}>{m}</option>)}</select></label><label>Access<select value={p.access_level} onChange={e => changeParticipant(i, { access_level: e.target.value })}>{["NONE", "PROGRESS", "COMMERCIAL"].map(a => <option key={a}>{a}</option>)}</select></label><label>Participating<input type="checkbox" checked={p.active} onChange={e => changeParticipant(i, { active: e.target.checked })} /></label></div>)}<button type="button" className="button-secondary" onClick={() => setParticipants([...participants, { organization_id: "", capability: null, access_level: "NONE", active: true }])}>Add participant</button></fieldset>
    <fieldset><legend>Role assignments</legend>{assignments.map((r, i) => <div className="commercial-row" key={i}><label>Role<select value={r.role} onChange={e => changeRole(i, { role: e.target.value })}>{roles.map(role => <option key={role} value={role}>{label(role)}</option>)}</select></label><label>Responsible organization<select required value={r.organization_id ?? ""} onChange={e => changeRole(i, { organization_id: e.target.value })}><option value="">Select organization</option>{orgOptions}</select></label><label>Scope<input value={r.scope} onChange={e => changeRole(i, { scope: e.target.value })} required /></label><label>Primary<input type="checkbox" checked={r.primary} onChange={e => changeRole(i, { primary: e.target.checked })} /></label><button type="button" className="button-quiet" onClick={() => setAssignments(assignments.filter((_, n) => n !== i))}>Remove role</button></div>)}<button type="button" className="button-secondary" onClick={() => setAssignments([...assignments, { role: "CUSTOMER_RELATIONSHIP_OWNER", scope: "OPPORTUNITY", primary: true, organization_id: "" }])}>Add responsibility</button></fieldset>
    <fieldset><legend>Solution components</legend>{components.map((c, i) => <div className="commercial-component" key={c.id ?? i}><div className="form-grid"><label>Product<select value={c.product_id ?? ""} onChange={e => { const product = products.find(p => p.id === e.target.value); changeComponent(i, { product_id: product?.id ?? null, sku_id: null, external_service: product ? null : "", owner_organization_id: product?.owner_organization_id ?? c.owner_organization_id }); }}><option value="">External service</option>{products.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Component name<input required value={c.name} onChange={e => changeComponent(i, { name: e.target.value })} /></label><label>Amount (USD)<input type="number" required min="0" step="0.01" value={c.amount} onChange={e => changeComponent(i, { amount: e.target.value })} /></label>{!c.product_id && <label>External service<input required value={c.external_service ?? ""} onChange={e => changeComponent(i, { external_service: e.target.value })} /></label>}{(["owner", "seller", "delivery", "billing"] as const).map(party => <label key={party}>{label(party)} organization<select required value={c[`${party}_organization_id`]} onChange={e => changeComponent(i, { [`${party}_organization_id`]: e.target.value })}><option value="">Select organization</option>{orgOptions}</select></label>)}</div></div>)}<button type="button" className="button-secondary" onClick={() => setComponents([...components, { name: "", product_id: null, sku_id: null, external_service: "", owner_organization_id: "", seller_organization_id: "", delivery_organization_id: "", billing_organization_id: "", amount: "0" }])}>Add solution component</button></fieldset>
    <button disabled={pending}>Save commercial structure</button></form>;
}
