import { useState, type FormEvent } from "react";
import { type Engagement, type Organization, type Agreements, type Term, label } from "./types";

export function TermsEditor({ data, organizations, agreements, terms, save, approve, pending }: { data: Engagement; organizations: Organization[]; agreements?: Agreements; terms: Term[]; save: (body: unknown) => void; approve: (id: string) => void; pending: boolean }) {
  const [scope, setScope] = useState("OPPORTUNITY");
  const [method, setMethod] = useState("PERCENT");
  const [compensation, setCompensation] = useState(false);
  const referral = data.engagement_model === "REFERRAL";
  const si = data.engagement_model === "SYSTEM_INTEGRATOR";
  const orgOptions = organizations.map(o => <option key={o.id} value={o.id}>{o.legal_name}</option>);
  function submit(e: FormEvent<HTMLFormElement>) {
    e.preventDefault(); const f = new FormData(e.currentTarget); const parameters: Record<string, unknown> = {};
    for (const key of ["fixed_unit_price", "discount_percentage", "customer_value", "customer_selling_value", "wholesale_value", "referral_rate", "settlement_policy", "compensation_beneficiary_id", "compensation_rate"]) if (f.get(key) !== null && f.get(key) !== "") parameters[key] = f.get(key);
    if (referral || compensation) parameters.eligibility = { component_ids: f.getAll("eligible_components"), amount: f.get("eligible_amount"), discounts: f.get("discounts"), taxes: f.get("taxes"), vendor_charges: f.get("vendor_charges"), credits: f.get("credits"), refunds: f.get("refunds") };
    if (si) {
      parameters.allocation_method = method;
      parameters.pool = { name: f.get("pool_name"), component_ids: f.getAll("pool_components"), gross_amount: f.get("pool_amount"), deducted_vendor_link_ids: data.vendor_links.filter(v => v.cost_treatment === "POOL_DEDUCTION").map(v => v.id), residual_beneficiary_id: f.get("residual") };
      if (method === "PERCENT") parameters.tcg_percentage = f.get("tcg_percentage");
      if (method === "FIXED") parameters.tcg_fixed = f.get("tcg_fixed");
      if (method === "ITEMIZED") parameters.allocations = f.getAll("pool_components").map(id => ({ component_id: id, beneficiary_id: f.get(`beneficiary_${id}`), amount: f.get(`amount_${id}`) }));
    }
    save({ expected_version: data.commercial_version, engagement_model: data.engagement_model, scope, opportunity_id: scope === "OPPORTUNITY" ? data.opportunity_id : null, contract_id: scope === "CONTRACT" ? f.get("contract") : null, partner_agreement_id: scope === "PARTNER" ? f.get("agreement") : null, sku_id: f.get("sku") || null, effective_from: f.get("from"), effective_until: f.get("until") || null, supersedes_id: f.get("supersedes") || null, parameters });
  }
  return <><form className="content-card compact-form" onSubmit={submit}><h2>Draft commercial terms</h2><p>Contract → opportunity → partner agreement → model default → catalog. A fixed price replaces catalog pricing; discounts do not stack.</p><div className="form-grid">
    <label>Scope<select value={scope} onChange={e => setScope(e.target.value)}>{["OPPORTUNITY", "CONTRACT", "PARTNER", "DEFAULT"].map(s => <option key={s}>{s}</option>)}</select></label>
    {scope === "CONTRACT" && <label>Contract<select name="contract" required><option value="">Select draft contract</option>{data.contracts.filter(c => c.status === "DRAFT").map(c => <option key={c.id} value={c.id}>{c.kind} · {c.id}</option>)}</select></label>}
    {scope === "PARTNER" && <label>Partner agreement<select name="agreement" required><option value="">Select agreement</option>{agreements?.partners.filter(a => a.engagement_model === data.engagement_model).map(a => <option key={a.id} value={a.id}>{a.id}</option>)}</select></label>}
    <label>Effective from<input name="from" type="date" required defaultValue={new Date().toISOString().slice(0, 10)} /></label><label>Effective until<input name="until" type="date" /></label><label>SKU scope (optional)<input name="sku" placeholder="SKU ID; blank applies to all components" /></label><label>Supersedes term<select name="supersedes"><option value="">New terms</option>{terms.filter(t => t.status === "APPROVED" && t.scope === scope && t.engagement_model === data.engagement_model).map(t => <option key={t.id} value={t.id}>v{t.version} · {t.id}</option>)}</select></label>
    <label>Fixed unit price (USD)<input name="fixed_unit_price" type="number" min="0" step="0.01" /></label><label>Agreed discount %<input name="discount_percentage" type="number" min="0" max="100" step="0.000001" /></label>
    {data.engagement_model === "RESELLER" ? <><label>Agreed wholesale value (USD)<input name="wholesale_value" type="number" min="0" step="0.01" /></label><label>Customer selling value (optional)<input name="customer_selling_value" type="number" min="0" step="0.01" placeholder="Undisclosed" /></label></> : <label>Customer contract value (USD)<input name="customer_value" type="number" min="0" step="0.01" required={si} /></label>}
    {referral && <label>Referral rate %<input name="referral_rate" type="number" min="0" max="100" step="0.000001" placeholder="10% model default; explicit 0 is allowed" /></label>}
    {data.engagement_model === "DIRECT" && <label>Explicit partner compensation<input type="checkbox" checked={compensation} onChange={e => setCompensation(e.target.checked)} /></label>}
    {compensation && <><label>Beneficiary<select name="compensation_beneficiary_id" required><option value="">Select associated partner</option>{orgOptions}</select></label><label>Compensation %<input name="compensation_rate" type="number" required min="0" max="100" step="0.000001" /></label></>}
    </div>
    {(referral || compensation) && <fieldset><legend>Explicit revenue eligibility</legend><div className="form-grid"><label>Eligible components<select name="eligible_components" multiple required>{data.components.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Eligible amount (USD)<input name="eligible_amount" type="number" required min="0" step="0.01" /></label>{["discounts", "taxes", "vendor_charges", "credits", "refunds"].map(k => <label key={k}>{label(k)} treatment<textarea name={k} required placeholder="Describe the agreed inclusion / exclusion" /></label>)}<label>Settlement / refund policy<textarea name="settlement_policy" placeholder="Required before payments or adjustments" /></label></div><p>Forecast only. Accrual requires a won opportunity and recorded conversion with actual eligible revenue.</p></fieldset>}
    {si && <fieldset><legend>SI allocation basis</legend><div className="form-grid"><label>Allocation method<select value={method} onChange={e => setMethod(e.target.value)}>{["PERCENT", "FIXED", "ITEMIZED"].map(m => <option key={m}>{m}</option>)}</select></label><label>Named pool<input name="pool_name" required placeholder="e.g. Agreed project services" /></label><label>Gross pool (USD)<input name="pool_amount" type="number" required min="0" step="0.01" /></label><label>Pool components<select multiple required name="pool_components">{data.components.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Residual beneficiary<select name="residual" required><option value="">Select TCG or the SI</option>{orgOptions}</select></label>{method === "PERCENT" && <label>TCG percentage of this pool<input name="tcg_percentage" type="number" min="0" max="100" step="0.000001" required /></label>}{method === "FIXED" && <label>Fixed mcube allocation (USD)<input name="tcg_fixed" type="number" min="0" step="0.01" required /></label>}</div>{method === "ITEMIZED" && data.components.map(c => <div key={c.id} className="commercial-row"><strong>{c.name}</strong><label>Beneficiary<select name={`beneficiary_${c.id}`}>{orgOptions}</select></label><label>Allocation (USD)<input name={`amount_${c.id}`} type="number" min="0" step="0.01" /></label></div>)}<p>Only vendor links explicitly marked as pool deductions reduce this pool. Other vendor obligations remain separate.</p></fieldset>}
    <button disabled={pending}>Save draft terms</button></form>
    <section className="content-card table-card"><h2>Term versions</h2><div className="table-scroll"><table><thead><tr><th>Scope / model</th><th>Effective</th><th>Version</th><th>Status</th><th /></tr></thead><tbody>{terms.map(t => <tr key={t.id}><td>{t.scope}<small>{t.engagement_model}</small></td><td>{t.effective_from}</td><td>v{t.version}</td><td>{t.status}</td><td>{t.status === "DRAFT" && <button disabled={pending} onClick={() => approve(t.id)}>Approve terms</button>}<details><summary>Agreed parameters</summary><pre className="commercial-json">{JSON.stringify(t.parameters, null, 2)}</pre></details></td></tr>)}</tbody></table></div></section></>;
}
