import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useState, type FormEvent } from "react";
import { Link, useSearchParams } from "react-router-dom";
import { getDeals, getPartners, getProducts } from "../api/client";
import { useAuth } from "../features/auth/AuthContext";
import { EngagementEditor } from "../features/commercial/EngagementEditor";
import { TermsEditor } from "../features/commercial/TermsEditor";
import { AgreementsEditor } from "../features/commercial/AgreementsEditor";
import { commercial, saveCommercial, dollars, type Agreements, type Commission, type Engagement, type Organization, type Snapshot, type Term, type Totals } from "../features/commercial/types";

function Amounts({ result, status, reseller }: { result: Totals; status: string; reseller?: boolean }) {
 return <><div className="commercial-totals">{([['Customer value', result.customer_value], ['TCG entitlement', result.tcg_entitlement], ['Partner benefit', result.partner_entitlement], ['Vendor obligations', result.vendor_cost], ['Commission expense', result.commission_expense], ['Reseller gross margin', result.reseller_gross_margin]] as const).filter(([name]) => name !== "Reseller gross margin" || reseller).map(([name, value]) => <div className="content-card" key={name}><small>{status} · {name}</small><strong>{dollars(value)}</strong></div>)}</div>{result.warnings.map(w => <p className="notice" key={w}>{w}</p>)}</>;
}
export function CommercialModelPage() {
 const { user } = useAuth(); const cache = useQueryClient(); const [params, setParams] = useSearchParams(); const id = params.get("deal") ?? "";
 const internal = Boolean(user?.is_superuser || user?.roles.some(r => r.startsWith("TCG_"))); const admin = Boolean(user?.is_superuser || user?.roles.includes("TCG_ADMIN"));
 const [tab, setTab] = useState(internal ? "Structure" : "Commissions"); const [preview, setPreview] = useState<Totals | null>(null);
 const deals = useQuery({ queryKey: ["deals"], queryFn: getDeals });
 const products = useQuery({ queryKey: ["products"], queryFn: getProducts, enabled: internal });
 const deal = deals.data?.find(d => d.id === id);
 const partners = useQuery({ queryKey: ["partners", "commercial"], queryFn: () => getPartners("status=ACTIVE&page_size=100"), enabled: internal });
 const organizations = useQuery({ queryKey: ["commercial", "organizations"], queryFn: () => commercial<Organization[]>("/organizations"), enabled: internal });
 const engagement = useQuery({ queryKey: ["commercial", "engagement", id], queryFn: () => commercial<Engagement>(`/opportunities/${id}`), enabled: internal && Boolean(id) });
 const agreements = useQuery({ queryKey: ["commercial", "agreements"], queryFn: () => commercial<Agreements>("/agreements"), enabled: admin });
 const terms = useQuery({ queryKey: ["commercial", "terms", id], queryFn: () => commercial<Term[]>(`/terms?opportunity_id=${id}`), enabled: admin && Boolean(id) });
 const snapshots = useQuery({ queryKey: ["commercial", "snapshots", id], queryFn: () => commercial<Snapshot[]>(`/opportunities/${id}/snapshots`), enabled: Boolean(id) });
 const commissions = useQuery({ queryKey: ["commercial", "commissions"], queryFn: () => commercial<Commission[]>("/commissions") });
 const review = useQuery({ queryKey: ["commercial", "review"], queryFn: () => commercial<{ id: string; reference: string; name: string }[]>("/migration-review"), enabled: internal });
 const action = useMutation({ mutationFn: ({ path, body, method }: { path: string; body: unknown; method?: string }) => saveCommercial(path, body, method), onSuccess: async () => { setPreview(null); await Promise.all([cache.invalidateQueries({ queryKey: ["commercial"] }), cache.invalidateQueries({ queryKey: ["deals"] })]); } });
 const calculate = useMutation({ mutationFn: () => saveCommercial<{ result: Totals }>(`/opportunities/${id}/preview`, {}), onSuccess: value => setPreview(value.result) });
 const data = engagement.data; const allOrganizations = organizations.data ?? [];
 const save = (path: string, body: unknown, method?: string) => action.mutate({ path, body, method });
 function conversion(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const f = new FormData(e.currentTarget); const snapshot = snapshots.data?.find(s => s.id === f.get("snapshot")); const eligibility = snapshot?.payload?.request.parameters.eligibility; save(`/opportunities/${id}/conversion`, { expected_version: data?.commercial_version, snapshot_id: f.get("snapshot"), evidence: f.get("evidence"), actual_eligibility: eligibility ? { ...eligibility, amount: f.get("amount") } : null }); }
 function ledger(e: FormEvent<HTMLFormElement>, c: Commission, kind: "payments" | "adjustments") { e.preventDefault(); const f = new FormData(e.currentTarget); save(`/commissions/${c.id}/${kind}`, kind === "payments" ? { expected_version: c.version, payment_reference: f.get("reference"), amount: f.get("amount") } : { event_key: f.get("reference"), amount: f.get("amount"), reason: f.get("reason") }); }
 const errors = [action.error, calculate.error, deals.error, organizations.error, engagement.error, terms.error, agreements.error, snapshots.error, commissions.error, review.error].filter(Boolean);
 return <div className="workspace-page commercial-workspace"><header className="page-heading"><span className="eyebrow">Commercial clarity</span><h1>{internal ? "Commercial model" : "My commercial benefit"}</h1><p>{internal ? "Define the parties, approve the economics, and preserve the agreed history." : "View your shared forecasts, accrued commission, and recorded payments."}</p></header>
 <div className="content-card compact-form"><label>Opportunity<select value={id} onChange={e => { setParams(e.target.value ? { deal: e.target.value } : {}); setPreview(null); }}><option value="">Select opportunity</option>{deals.data?.map(d => <option key={d.id} value={d.id}>{d.reference} · {d.name} · {d.engagement_model ?? "Review required"}</option>)}</select></label>{deal && <p><span className="status-pill">{deal.approval_status}</span> · Commercial version {deal.commercial_version} · {deal.stage}</p>}</div>
 <nav className="section-tabs" aria-label="Commercial workspace">{(internal ? ["Structure", ...(admin ? ["Terms", "Agreements"] : []), "Snapshots", "Commissions", "Migration review"] : ["Snapshots", "Commissions"]).map(t => <button key={t} aria-pressed={t === tab} className={t === tab ? "active" : "button-secondary"} onClick={() => setTab(t)}>{t}</button>)}</nav>
 {errors.map((error, i) => <p key={i} className="form-alert form-alert--error" role="alert">{error?.message}</p>)}{action.isSuccess && <p role="status" className="notice">Saved. Current records have been refreshed.</p>}
 {engagement.isFetching && id && <p role="status">Loading commercial structure…</p>}
 {tab === "Structure" && data && deal && <EngagementEditor key={`${id}:${data.commercial_version}`} data={data} deal={deal} organizations={allOrganizations} partners={partners.data?.items ?? []} products={products.data ?? []} pending={action.isPending} save={body => save(`/opportunities/${id}`, body, "PUT")} />}
 {tab === "Terms" && data && <TermsEditor key={`${id}:${data.commercial_version}`} data={data} organizations={allOrganizations} agreements={agreements.data} terms={terms.data ?? []} pending={action.isPending} save={body => save("/terms", body)} approve={term => save(`/terms/${term}/approve`, { expected_version: data.commercial_version })} />}
 {tab === "Agreements" && admin && <AgreementsEditor data={data} organizations={allOrganizations} agreements={agreements.data} partners={partners.data?.items ?? []} save={save} pending={action.isPending} />}
 {["Structure", "Terms", "Snapshots"].includes(tab) && !id && <div className="empty-state"><h2>Select an opportunity</h2><p>Choose a deal above, or <Link to="/deals">register a new opportunity</Link>.</p></div>}
 {tab === "Snapshots" && id && <>{internal && <section className="content-card compact-form"><h2>Current forecast</h2><p>Draft preview uses currently approved terms. Finalized quote snapshots remain unchanged.</p><button disabled={calculate.isPending} onClick={() => calculate.mutate()}>Calculate preview</button></section>}{preview && <Amounts result={preview} status="FORECAST" reseller={deal?.engagement_model === "RESELLER"} />}{snapshots.data?.map(s => <section key={s.id} className="content-card compact-form"><h2>Snapshotted · quote revision {s.revision}</h2><small className="commercial-reference">{s.id}</small>{s.payload ? <Amounts result={s.payload.result} status="SNAPSHOTTED" reseller={deal?.engagement_model === "RESELLER"} /> : <p>Your forecast entitlement: <strong>{dollars(s.own_entitlement)}</strong></p>}</section>)}{!snapshots.data?.length && <p className="empty-state">No finalized commercial snapshots yet.</p>}{internal && Boolean(snapshots.data?.length) && <form className="content-card compact-form" onSubmit={conversion}><h2>Record customer / project conversion</h2><p>A win alone does not accrue commission. Actual eligibility retains the treatments and components frozen in the selected snapshot.</p><label>Agreed snapshot<select required name="snapshot">{snapshots.data?.map(s => <option key={s.id} value={s.id}>Revision {s.revision} · {s.id}</option>)}</select></label><label>Conversion evidence<textarea name="evidence" required minLength={3} placeholder="Accepted contract, order or verified customer/project evidence" /></label><label>Actual eligible revenue (USD)<input name="amount" type="number" min="0" step="0.01" required={deal?.engagement_model === "REFERRAL"} /></label><button disabled={action.isPending}>Record conversion</button></form>}</>}
 {tab === "Commissions" && <>{commissions.data?.filter(c => !id || c.opportunity_id === id).map(c => <section key={c.id} className="content-card compact-form"><h2>{c.status === "PAID" ? "Paid commission" : "Accrued commission"}</h2><p>{dollars(c.eligible_amount)} eligible × {c.rate}% · original accrual {dollars(c.amount)}</p><div className="commercial-totals">{[["Net accrued", c.net_accrued], ["Recorded paid", c.paid], ["Outstanding", c.outstanding]].map(([title, value]) => <div key={title}><small>{title}</small><strong>{dollars(value)}</strong></div>)}</div><p>Settlement policy: {c.settlement_policy || "Not configured. Payments and adjustments are blocked."}</p>{admin && c.settlement_policy && <div className="commercial-forms"><form className="compact-form" onSubmit={e => ledger(e, c, "payments")}><h3>Record payment</h3><label>Payment reference<input name="reference" required minLength={3} /></label><label>Amount (USD)<input name="amount" type="number" min="0.01" step="0.01" required /></label><button disabled={action.isPending}>Record payment</button></form><form className="compact-form" onSubmit={e => ledger(e, c, "adjustments")}><h3>Credit / refund adjustment</h3><label>Unique event reference<input name="reference" required minLength={3} /></label><label>Signed adjustment (USD)<input name="amount" type="number" step="0.01" required /></label><label>Reason<textarea name="reason" required minLength={3} /></label><button disabled={action.isPending}>Append adjustment</button></form></div>}</section>)}{!commissions.data?.some(c => !id || c.opportunity_id === id) && <div className="empty-state"><h2>No accrued commission</h2><p>Forecasts are shown under Snapshots. Accrual requires a qualifying win and conversion evidence.</p></div>}</>}
 {tab === "Migration review" && <section className="content-card compact-form"><h2>Legacy records requiring review</h2><p>Historical totals are preserved. Confirm the model, participants, responsibilities and explicit terms before new commercial actions.</p>{review.data?.map(d => <button className="button-secondary" key={d.id} onClick={() => { setParams({ deal: d.id }); setTab("Structure"); }}>{d.reference} · {d.name}</button>)}{review.data?.length === 0 && <p>No opportunities await classification.</p>}</section>}
 </div>;
}
