export const partnerPaths = [
  { code: "REFERRAL", name: "Referral partner", verb: "Connect.", icon: "people", tag: "Turn relationships into opportunity", description: "Open new doors. Introduce businesses to TCG and let our team take the opportunity forward.", audience: "Advisors, consultants, and industry connectors with an established business network.", requirements: "A registered business, a relevant network, and qualified customer introductions.", incentive: "Referral commission on explicitly eligible revenue, subject to approved agreement and successful conversion.", benefits: ["A simple opportunity referral process", "Visibility into approved referral progress", "TCG-led sales and implementation"], },
  { code: "RESELLER", name: "Reseller partner", verb: "Grow.", icon: "growth", tag: "Make more possible for your customers", description: "Bring TCG solutions to your market and build lasting value through your customer relationships.", audience: "Technology providers and sales organizations with enterprise customer relationships.", requirements: "A registered business, a sales capability, and an agreed go-to-market plan.", incentive: "Earn the margin between your customer selling price and your agreed TCG wholesale price.", benefits: ["An expanded enterprise solution portfolio", "Ownership of your customer relationship", "Agreed wholesale commercial terms"], },
  { code: "SYSTEM_INTEGRATOR", name: "System integrator", verb: "Build.", icon: "layers", tag: "Your expertise. Our technology.", description: "Combine your delivery expertise with TCG platforms to solve your customers’ most complex challenges.", audience: "Consultancies and delivery teams with integration, data, or industry expertise.", requirements: "A registered business, implementation expertise, and an agreed project delivery scope.", incentive: "Project-based service value and allocations agreed in your individual contract.", benefits: ["Joint solution and delivery opportunities", "Integration with TCG platforms", "Project-specific roles and commercial terms"], },
];
export const benefits = [
  { icon: "growth", title: "Unlock new growth", text: "Expand your offering with enterprise AI and analytics. Turn your market knowledge into new business opportunities." },
  { icon: "spark", title: "Build with powerful technology", text: "Bring together your expertise and TCG’s intelligent platforms to create solutions that make a difference." },
  { icon: "people", title: "Succeed, together", text: "Work with a team that understands your ambition. Align on opportunities, delivery, and a shared path forward." },
];
export const stories = [
  { company: "Northstar Consulting", initials: "NC", person: "Alex Morgan", role: "Managing Partner", type: "System integrator", quote: "Bringing our industry expertise together with TCG’s technology gives us a new way to solve our customers’ most important challenges.", metric: "One team.", metricLabel: "A shared approach to customer success", detail: "This illustrative scenario shows a consulting team combining its implementation expertise with TCG analytics. The teams agree on delivery ownership and commercial terms before working toward a shared customer outcome." },
  { company: "Meridian Technologies", initials: "MT", person: "Priya Shah", role: "Director of Partnerships", type: "Reseller partner", quote: "The opportunity to add enterprise analytics to our portfolio helps us have a much more valuable conversation with our customers.", metric: "More possibility.", metricLabel: "An expanded enterprise solution portfolio", detail: "This illustrative reseller scenario shows a technology provider introducing TCG solutions to its customers. The reseller owns the customer relationship and sets its customer price under an agreed wholesale arrangement." },
  { company: "Apex Advisory", initials: "AA", person: "Daniel Lee", role: "Founder", type: "Referral partner", quote: "We know our customers’ challenges. A clear referral path lets us connect them with the right technology and the right people.", metric: "Better connected.", metricLabel: "Relationships that open new doors", detail: "This illustrative referral scenario shows an advisor introducing a qualified opportunity. TCG leads the sales and delivery process, while the advisor follows approved progress and earns compensation under the agreed referral terms." },
];
export const faqs = [
  ["Which partnership is right for my business?", "Choose Referral if you introduce opportunities, Reseller if you own the customer sales relationship, or System Integrator if you implement solutions. Start with your primary interest; TCG can discuss additional capabilities during review."],
  ["Are these partnership types ranked tiers?", "No. Referral, Reseller, and System Integrator are distinct ways to work with TCG, with different responsibilities and commercial arrangements. Choose the model that fits how you serve customers."],
  ["What do I need to apply?", "Have your company name, business email, country, primary contact details, and preferred partnership type ready. You’ll also create a password for your future partner workspace."],
  ["What happens after I submit my application?", "TCG reviews your company and partnership interests. The team can contact your primary administrator for clarification, agree on the appropriate terms, and approve workspace access when onboarding is complete."],
  ["How are commercial benefits determined?", "Resellers earn their agreed customer-to-wholesale margin. Referral benefits apply to explicitly eligible revenue after successful conversion. System integrator allocations follow project terms. Exact eligibility and commercial conditions are agreed with TCG."],
];

